#!/usr/bin/env python3
from random import choice
from string import (ascii_lowercase as low,
                    ascii_uppercase as high)

import sys

def gen_name(length=5):
    length = int(length)
    if length <= 0:
        raise TypeError('length must be > 0')
    # s = ''.join([(choice(high) if i == 0 else choice(low))
    # 	      for i in range(length)])
    s = ''
    for i in range(length):
        if i == 0:
            s += choice(high)
        else:
            s += choice(low)
    return s

print('ARGS:', sys.argv)

# very simple check
if len(sys.argv) != 2:
    print('There must be exactly one argument (length)',
          file=sys.stderr)
    exit(-1)

namelen = sys.argv[1]
print('Random Name:', gen_name(namelen))
